# Generated by Django 4.2.17 on 2025-01-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="image",
            field=models.ImageField(null=True, upload_to="announcements/"),
        ),
    ]
