# Generated by Django 4.2.17 on 2025-01-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_announcement_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpagecontent",
            name="goals",
        ),
        migrations.RemoveField(
            model_name="aboutpagecontent",
            name="target_group",
        ),
        migrations.RemoveField(
            model_name="aboutpagecontent",
            name="values",
        ),
    ]
