# Generated by Django 4.2.17 on 2025-01-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_aboutpagecontent_goals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="isCourse",
            field=models.BooleanField(default=True),
        ),
    ]
