# Generated by Django 4.2.17 on 2025-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_activity_iscourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitymedia",
            name="image",
            field=models.ImageField(upload_to="activities/"),
        ),
    ]
