# Generated by Django 4.2.17 on 2025-01-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_activitymedia_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="isCourse",
            new_name="is_course",
        ),
        migrations.AddField(
            model_name="activitymedia",
            name="main_pic",
            field=models.BooleanField(default=False),
        ),
    ]
