# Generated by Django 4.2.17 on 2025-01-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_iscourse_activity_is_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="publish_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registration_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tender",
            name="publish_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tenderregistration",
            name="registration_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="visit_date",
            field=models.DateField(),
        ),
    ]
