# Generated by Django 4.2.17 on 2025-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_visitmedia_main_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="is_course",
            field=models.BooleanField(default=False),
        ),
    ]
