# Generated by Django 4.2.17 on 2025-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_activity_is_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="seasonal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activity",
            name="is_course",
            field=models.BooleanField(default=True),
        ),
    ]
