# Generated by Django 4.2.17 on 2025-01-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_activity_seasonal_alter_activity_is_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("run", "Run"),
                    ("workshop", "Workshop"),
                    ("exhibition", "Exhibition"),
                ],
                default="Workshop",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventmedia",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="event_media_upload_path"
            ),
        ),
        migrations.CreateModel(
            name="ExhibitionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "drawing",
                    models.ImageField(blank=True, null=True, upload_to="exhibition/"),
                ),
                (
                    "exhibition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="main.event",
                    ),
                ),
            ],
        ),
    ]
